version: "3.9"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - compose-bridge

  app-nodes:
      image: valterlafuentejr/lafuente-books:v1  
      container_name: app-nodes
      networks:
       - compose-bridge
      ports:
        - 3000:3000
      depends_on:
        - mongodb
        
networks:
  compose-bridge:
    driver: bridge